



CREATE TABLE AGENCIA (
ID_AGENCIA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
CNPJ VARCHAR(40) NOT NULL,
NOME VARCHAR(40) NOT NULL,
TELEFONE INT NOT NULL,
EMAIL VARCHAR(40) NOT NULL
)

CREATE TABLE DESTINOS (
ID_DESTINOS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
CIDADE VARCHAR(40) NOT NULL,
PAIS VARCHAR(40) NOT NULL,
ESTADO VARCHAR(40) NOT NULL,
VALOR INT NOT NULL,
FOREIGN KEY(ID_AGENCIA) REFERENCES AGENCIA (ID_AGENCIA)

)

CREATE TABLE PROMO (
ID_PROMO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
VALOR_DESCONTO INT NOT NULL,
FOREIGN KEY(ID_DESTINOS) REFERENCES DESTINOS (ID_DESTINOS)

)



